config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tests do
    resources :questions, shallow: true do
      resources :answers, shallow: true, except: :index
    end

    member do
       post :start
    end
  end

  resources :results, only: %i[show update] do
     member do
       get :result
     end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :number_of_answers, on: :create

  private

  def number_of_answers
    errors.add(:answers, 'Too many answers') if question.answers.count >= 4
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers
  belongs_to :test

  validates :body, presence: true
end

app/models/result.rb
# frozen_string_literal: true

class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question, on: %i[create update]

  SUCCESS_RATE = 85

  def accept!(answer_ids)
    self.score += 1 if correct_answer?(answer_ids)

    save!
  end

  def success?
    score * 100 / number_of_questions >= SUCCESS_RATE
  end

  def completed?
    current_question.nil?
  end

  def question_number
    test.questions.index(current_question) + 1
  end

  def number_of_questions
    test.questions.count
  end

  private

  def set_current_question
    current_question ? set_next_question : set_first_question
  end

  def set_first_question
    self.current_question = test.questions.first
  end

  def set_next_question
    self.current_question = test.questions
                                .order(:id)
                                .where(
                                  'id > :id',
                                  id: current_question.id
                                ).first
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  has_many :questions
  has_many :results
  has_many :users, through: :results
  belongs_to :category
  belongs_to :author, class_name: 'User'

  scope :easy, -> { where(level: 0..1) }
  scope :middle, -> { where(level: 2..4) }
  scope :difficult, -> { where(level: 5..Float::INFINITY) }
  scope :categories_by_name, lambda { |name|
                               joins(:category).where(categories: {
                                                        title: name
                                                      })
                             }

  validates :title, presence: true
  validates :title, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true,
                                    greater_than_or_equal_to: 0 }

  def self.test_by_category(category_title)
    categories_by_name(category_title).order(title: :desc).pluck(:title)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :results
  has_many :tests, through: :results
  has_many :own_tests, class_name: 'Test', foreign_key: :author_id

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_result(test)
    results.order(id: :desc).find_by(test_id: test.id)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    answer = @question.answers.new(answer_params)

    if answer.save
      redirect_to answer
    else
      redirect_to action: :new
    end
  end

  def update
    if @answer.update_attributes(answer_params)
      redirect_to @answer
    else
      redirect_to action: :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to action: :index
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :find_test, only: %i[index new create]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_not_found

  def index
    @questions = @test.questions
  end

  def show; end

  def new
    @question = @test.question.new
  end

  def edit; end

  def create
    question = @test.questions.new(body: question_params[:body])

    if question.save
      redirect_to question
    else
      redirect_to action: :new
    end
  end

  def update
    if @question.update_attributes(question_params)
      redirect_to @question
    else
      redirect_to action: :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to action: :index
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_not_found
    render file: "#{Rails.root}/public/404", status: :not_found
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/controllers/results_controller.rb
# frozen_string_literal: true

class ResultsController < ApplicationController
  before_action :find_result, only: %i[show update result]

  def show; end

  def result; end

  def update
    @result.accept!(params[:answer_ids])
    if @result.completed?
      redirect_to result_result_path(@result)
    else
      render :show
    end
  end

  private

  def find_result
    @result = Result.find(params[:id])
  end
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :find_test, only: %i[show edit update destroy start]

  def index
    @tests = Test.all
  end

  def show; end

  def edit; end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      redirect_to @test
    else
      render :new
    end
  end

  def update
    if @test.update_attributes(test_params)
      redirect_to @test
    else
      render :edit
    end
  end

  def destroy
    @test.destroy
    redirect_to action: :index
  end

  def start
    user = User.first
    user.tests << @test
    redirect_to user.test_result(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def test_params
    params.require(:test).permit(:title, :level, :category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'Github', "https://github.com/#{author}/#{repo}", target: :blank
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "New question in '#{@test.title}' test"
    else
      "Edit question in '#{question.test.title}' test"
    end
  end
end

app/views/answers/_answer.html.haml
%tr
  %td
    = link_to answer.body, answer_path(answer)
  %td
    = link_to 'Edit', edit_answer_path(answer)
  %td
    = link_to 'Delete', answer_path(answer),
                        method: :delete,
                        data: { confirm: 'Are you sure?' }

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer] do |form| %>
  <%= render 'shared/errors', resource: @answer %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body, id: :answer_body %>
  </p>
  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/answers/edit.html.haml
%h1
  = "Edit answer for '#{@answer.question.body}' question"
= render 'form'
%p
  = link_to 'Back', question_path(@answer.question)

app/views/answers/new.html.haml
%h1
  = "New answer for '#{@question.body}' question"
= render 'form'
%p
  = link_to 'Back', question_path(@answer.question)

app/views/answers/show.html.haml
%p
  = 'Body:'
  = @answer.body
%p
  = 'Correct:'
  = @answer.correct

= link_to 'Edit', edit_answer_path(@answer)
= link_to 'Back', test_path(@answer.question.test)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: [@test, @question] do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body, id: :question_body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/questions/_question.html.haml
%tr
  %td
    = link_to question.body, question_path(question)
  %td
    = link_to 'Edit', edit_question_path(question)
  %td
    = link_to 'Delete', question_path(question),
                        method: :delete,
                        data: { confirm: 'Are you sure?' }

app/views/questions/edit.html.haml
= question_header(@question)
= render 'form'
%p
  = link_to 'Back', test_path(@question.test)

app/views/questions/index.html.haml
%table
  %tr
    %th
      = 'Question'
    %th
    %th

  = render @questions

app/views/questions/new.html.haml
= question_header(@question)
= render 'form'
%p
  = link_to 'Back', test_path(@question.test)

app/views/questions/show.html.haml
%p
  = @question.body
%p
  = 'Answers:'
  %table
    %tr
      %th
        = 'Answers'
      %th
      %th
    = render @question.answers

= link_to 'New answer', new_question_answer_path(@question)
= link_to 'Edit', edit_question_path(@question)
= link_to 'Back', test_path(@question.test)

app/views/results/_form.html.erb
<%= form_with url: result_path(@result), local: true, method: :put do |form|%>
  <%= form.collection_check_boxes :answer_ids, @result.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/results/result.html.haml
%h1
  = 'Test completed'

- if @result.success?
  <p style="color: green">Success</p>
- else
  <p style="color: red">Fail</p>
= link_to 'Back', tests_path

app/views/results/show.html.haml
%h1
  = "Test: #{@result.test.title}, question #{@result.question_number} / #{@result.number_of_questions}"
%p
  = "Current question: #{@result.current_question.body}"

= render 'form'

app/views/shared/_errors.html.haml
- if resource.errors.present?
  %div
    %h2
      = pluralize(resource.errors.count, 'Error')
    %ul
      - resource.errors.full_messages.each do |message|
        %li
          = message

app/views/shared/_footer.html.haml
= '-----'
%p
  = current_year
%p
  = 'Author: Yu Ushakova'
%p
  = github_url('ushakova', 'TestGuru')
%p
  = link_to 'Учебный проект в онлайн-школе Thinknetica', 'https://thinknetica.com'